# Generated by Django 5.1.4 on 2024-12-25 12:05

import django.db.models.deletion
import shoplist.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=shoplist.models.image_path)),
            ],
        ),
        migrations.CreateModel(
            name='SaleSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_code', models.CharField(max_length=10)),
                ('description_text', models.CharField(max_length=150)),
                ('bought_amount', models.IntegerField(default=0)),
                ('order_amount', models.IntegerField()),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shoplist.image')),
                ('sale_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoplist.salesession')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='sale_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoplist.salesession'),
        ),
    ]
