# Generated by Django 5.1.4 on 2024-12-29 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoplist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesession',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
