# Generated by Django 5.1.4 on 2025-01-31 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoplist', '0002_salesession_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesession',
            name='sale_date',
            field=models.DateField(unique=True),
        ),
    ]
