# Generated by Django 5.1.4 on 2025-01-31 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoplist', '0003_alter_salesession_sale_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesession',
            name='last_update',
        ),
    ]
