# Generated by Django 5.1.4 on 2025-03-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoplist', '0005_product_is_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='note',
            field=models.CharField(default='', max_length=150),
        ),
    ]
